### ISSUE TITLE
Missing Grate wood Trees

### ISSUE THREAD

**Issue by F1tZ81** [DungeonsAndShotguns/DS-Launcher#6]
If you plant a greatwood sapling it disappears. Also, when you are chopping greatwood leaves they turn into silverwood leaves, but still drop greatwood saplings.

**Comment by F1tZ81** [comment]
Ben do you know if this is still an issue?

**Comment by 7h3phr33k** [comment]
as far as I know it is.  We haven't updated thaumcraft afaik since we installed it and 2 weeks ago I experienced the leaves changing.  I haven't tried planting any thaumcraft saplings yet, but I do know that the plants that grow in the desert and under silverwood trees disappear when you look at them!

**Comment by F1tZ81** [comment]
wrong project
